CREATE OR REPLACE FUNCTION DATE_TO_UNIX_TS( PDate IN date ) RETURN NUMBER IS

    l_unix_ts NUMBER;

BEGIN

    l_unix_ts := ( PDate - date '1970-01-01' ) * 60 * 60 * 24;
    RETURN ROUND(l_unix_ts);

END;

ALTER TABLE SAKORA_MEMBERSHIP ADD INPUT_INT NUMBER(10,0) NULL;
UPDATE SAKORA_MEMBERSHIP SET INPUT_INT = DATE_TO_UNIX_TS(INPUT_TIME);
ALTER TABLE SAKORA_MEMBERSHIP DROP COLUMN INPUT_TIME;
ALTER TABLE SAKORA_MEMBERSHIP RENAME COLUMN INPUT_INT TO INPUT_TIME;
ALTER TABLE SAKORA_MEMBERSHIP MODIFY INPUT_TIME NUMBER(10,0) DEFAULT NULL;

ALTER TABLE SAKORA_PERSON ADD INPUT_INT NUMBER(10,0) NULL;
UPDATE SAKORA_PERSON SET INPUT_INT = DATE_TO_UNIX_TS(INPUT_TIME);
ALTER TABLE SAKORA_PERSON DROP COLUMN INPUT_TIME;
ALTER TABLE SAKORA_PERSON RENAME COLUMN INPUT_INT TO INPUT_TIME;
ALTER TABLE SAKORA_PERSON MODIFY INPUT_TIME NUMBER(10,0) DEFAULT NULL;

ALTER TABLE SAKORA_SESSION ADD INPUT_INT NUMBER(10,0) NULL;
UPDATE SAKORA_SESSION SET INPUT_INT = DATE_TO_UNIX_TS(INPUT_TIME);
ALTER TABLE SAKORA_SESSION DROP COLUMN INPUT_TIME;
ALTER TABLE SAKORA_SESSION RENAME COLUMN INPUT_INT TO INPUT_TIME;
ALTER TABLE SAKORA_SESSION MODIFY INPUT_TIME NUMBER(10,0) DEFAULT NULL;
