<?xml version="1.0"?>
<wsdl:definitions name="MEMBERSHIPMANAGEMENTSERVICE.1" targetNamespace="http://xmlns.oracle.com/Enterprise/HCM/services/SAE_MEMBERSHIP_SERVICE" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:readMembershipsFromSavPointReq.V1="http://www.imsglobal.org/services/es/mms2p0/xsd/imsmms_v2p0" xmlns:readMembershipsFromSavPointRes.V1="http://www.imsglobal.org/services/es/mms2p0/xsd/imsmms_v2p0" xmlns:readMembershipsRequest.V1="http://www.imsglobal.org/services/es/mms2p0/xsd/imsmms_v2p0" xmlns:readMembershipsResponse.V1="http://www.imsglobal.org/services/es/mms2p0/xsd/imsmms_v2p0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://xmlns.oracle.com/Enterprise/HCM/services/SAE_MEMBERSHIP_SERVICE" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2002/12/policy">
  <wsp:UsagePolicy wsdl:Required="true"/>
  <plnk:partnerLinkType name="MEMBERSHIPMANAGEMENTSERVICE_PartnerLinkType">
    <plnk:role name="MEMBERSHIPMANAGEMENTSERVICE_Provider">
      <plnk:portType name="tns:MEMBERSHIPMANAGEMENTSERVICE_PortType"/>
    </plnk:role>
  </plnk:partnerLinkType>
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.imsglobal.org/services/es/mms2p0/xsd/imsmms_v2p0" schemaLocation="readMembershipsRequest.V1.xsd"/>
      <xsd:import namespace="http://www.imsglobal.org/services/es/mms2p0/xsd/imsmms_v2p0" schemaLocation="readMembershipsResponse.V1.xsd"/>
      <xsd:import namespace="http://www.imsglobal.org/services/es/mms2p0/xsd/imsmms_v2p0" schemaLocation="readMembershipsFromSavPointReq.V1.xsd"/>
      <xsd:import namespace="http://www.imsglobal.org/services/es/mms2p0/xsd/imsmms_v2p0" schemaLocation="readMembershipsFromSavPointRes.V1.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="request.V1"/>
  <wsdl:message name="response.V1"/>
  <wsdl:message name="readMembershipsRequest.V1">
    <wsdl:documentation>Memberships Request Msg</wsdl:documentation>
    <wsdl:part element="readMembershipsRequest.V1:sourcedId" name="parameter"/>
  </wsdl:message>
  <wsdl:message name="readMembershipsResponse.V1">
    <wsdl:documentation>Read Memberships Response Msg</wsdl:documentation>
    <wsdl:part element="readMembershipsResponse.V1:dataFile" name="parameter"/>
  </wsdl:message>
  <wsdl:message name="readMembershipsFromSavPointReq.V1">
    <wsdl:part element="readMembershipsFromSavPointReq.V1:fromSavePoint" name="parameter"/>
  </wsdl:message>
  <wsdl:message name="readMembershipsFromSavPointRes.V1">
    <wsdl:part element="readMembershipsFromSavPointRes.V1:dataFile" name="parameter"/>
  </wsdl:message>
  <wsdl:portType name="MEMBERSHIPMANAGEMENTSERVICE_PortType">
    <wsdl:operation name="changeMembershipIdentifier">
      <wsdl:documentation>Change Membership Identifier</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="createByProxyMembership">
      <wsdl:documentation>Create By Proxy Membership</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="createMembership">
      <wsdl:documentation>Create Membership</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="deleteMembership">
      <wsdl:documentation>Delete Membership</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="discoverMembershipIds">
      <wsdl:documentation>Discover Membership Ids</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="readAllMembershipIds">
      <wsdl:documentation>Read All Membership Ids</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="readMembershipIdsForCollection">
      <wsdl:documentation>Read Membership Ids Collection</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="readMembershipIdsForPersonWithRole">
      <wsdl:documentation>Read Membership Ids For roles</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="readMembershipIdsFromSavePoint">
      <wsdl:documentation>Read Membership Ids from save</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:request.V1" name="request.V1"/>
    </wsdl:operation>
    <wsdl:operation name="readMembershipIdsForPerson">
      <wsdl:documentation>Read Membership Ids For Person</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="readMemberships">
      <wsdl:documentation>Membership Snapshot</wsdl:documentation>
      <wsdl:input message="tns:readMembershipsRequest.V1" name="readMembershipsRequest.V1"/>
      <wsdl:output message="tns:readMembershipsResponse.V1" name="readMembershipsResponse.V1"/>
    </wsdl:operation>
    <wsdl:operation name="readMembershipsFromSavePoint">
      <wsdl:documentation>Memberships from save point</wsdl:documentation>
      <wsdl:input message="tns:readMembershipsFromSavPointReq.V1" name="readMembershipsFromSavPointReq.V1"/>
      <wsdl:output message="tns:readMembershipsFromSavPointRes.V1" name="readMembershipsFromSavPointRes.V1"/>
    </wsdl:operation>
    <wsdl:operation name="readMembership">
      <wsdl:documentation>Read Membership</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="replaceMembership">
      <wsdl:documentation>Replace Membership</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="updateMembership">
      <wsdl:documentation>Update Membership</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="MEMBERSHIPMANAGEMENTSERVICE_Binding" type="tns:MEMBERSHIPMANAGEMENTSERVICE_PortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="changeMembershipIdentifier">
      <soap:operation soapAction="changeMembershipIdentifier.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="createByProxyMembership">
      <soap:operation soapAction="createByProxyMembership.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="createMembership">
      <soap:operation soapAction="createMembership.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="deleteMembership">
      <soap:operation soapAction="deleteMembership.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="discoverMembershipIds">
      <soap:operation soapAction="discoverMembershipIds.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readAllMembershipIds">
      <soap:operation soapAction="readAllMembershipIds.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readMembershipIdsForCollection">
      <soap:operation soapAction="readMembershipIdsForCollection.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readMembershipIdsForPersonWithRole">
      <soap:operation soapAction="readMembershipIdsForPersonWithRole.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readMembershipIdsFromSavePoint">
      <soap:operation soapAction="readMembershipIdsFromSavePoint.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readMembershipIdsForPerson">
      <soap:operation soapAction="readMembershipIdsForPerson.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readMemberships">
      <soap:operation soapAction="READMEMBERSHIPS.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="readMembershipsRequest.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="readMembershipsResponse.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readMembershipsFromSavePoint">
      <soap:operation soapAction="READMEMBERSHIPSFROMSAVEPOINT.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="readMembershipsFromSavPointReq.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="readMembershipsFromSavPointRes.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readMembership">
      <soap:operation soapAction="readMembership.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="replaceMembership">
      <soap:operation soapAction="replaceMembership.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="updateMembership">
      <soap:operation soapAction="updateMembership.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="MembershipManagementServiceSyncService">
    <wsdl:documentation>Membership Snapshot Service</wsdl:documentation>
    <wsdl:port binding="tns:MEMBERSHIPMANAGEMENTSERVICE_Binding" name="MEMBERSHIPMANAGEMENTSERVICE_Port">
      <soap:address location="http://ORACLE_ENDPOINT"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>