<?xml version="1.0"?>
<wsdl:definitions name="PERSONMANAGEMENTSERVICE.1" targetNamespace="http://xmlns.oracle.com/Enterprise/HCM/services/PersonManagementServiceSyncService.1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:readPersonsFromSavePointReq.V1="http://www.imsglobal.org/services/es/pms2p0/xsd/imspms_v2p0" xmlns:readPersonsFromSavePointRes.V1="http://www.imsglobal.org/services/es/pms2p0/xsd/imspms_v2p0" xmlns:readPersonsRequest.V1="http://www.imsglobal.org/services/es/pms2p0/xsd/imspms_v2p0" xmlns:readPersonsResponse.V1="http://www.imsglobal.org/services/es/pms2p0/xsd/imspms_v2p0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://xmlns.oracle.com/Enterprise/HCM/services/PersonManagementServiceSyncService.1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2002/12/policy">
  <wsp:UsagePolicy wsdl:Required="true"/>
  <plnk:partnerLinkType name="PERSONMANAGEMENTSERVICE_PartnerLinkType">
    <plnk:role name="PERSONMANAGEMENTSERVICE_Provider">
      <plnk:portType name="tns:PERSONMANAGEMENTSERVICE_PortType"/>
    </plnk:role>
  </plnk:partnerLinkType>
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.imsglobal.org/services/es/pms2p0/xsd/imspms_v2p0" schemaLocation="readPersonsRequest.V1.xsd"/>
      <xsd:import namespace="http://www.imsglobal.org/services/es/pms2p0/xsd/imspms_v2p0" schemaLocation="readPersonsResponse.V1.xsd"/>
      <xsd:import namespace="http://www.imsglobal.org/services/es/pms2p0/xsd/imspms_v2p0" schemaLocation="readPersonsFromSavePointReq.V1.xsd"/>
      <xsd:import namespace="http://www.imsglobal.org/services/es/pms2p0/xsd/imspms_v2p0" schemaLocation="readPersonsFromSavePointRes.V1.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="request.V1"/>
  <wsdl:message name="response.V1"/>
  <wsdl:message name="readPersonsRequest.V1">
    <wsdl:part element="readPersonsRequest.V1:sourcedId" name="parameter"/>
  </wsdl:message>
  <wsdl:message name="readPersonsResponse.V1">
    <wsdl:part element="readPersonsResponse.V1:dataFile" name="parameter"/>
  </wsdl:message>
  <wsdl:message name="readPersonsFromSavePointReq.V1">
    <wsdl:part element="readPersonsFromSavePointReq.V1:fromSavePoint" name="parameter"/>
  </wsdl:message>
  <wsdl:message name="readPersonsFromSavePointRes.V1">
    <wsdl:part element="readPersonsFromSavePointRes.V1:dataFile" name="parameter"/>
  </wsdl:message>
  <wsdl:portType name="PERSONMANAGEMENTSERVICE_PortType">
    <wsdl:operation name="changePersonIdentifier">
      <wsdl:documentation>Change Person Identifier</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="createByProxyPerson">
      <wsdl:documentation>Create by proxy person</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="createPerson">
      <wsdl:documentation>Create Person</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="deletePerson">
      <wsdl:documentation>Delete person</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="discoverPersonIds">
      <wsdl:documentation>Discover Person Ids</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="readAllPersonIds">
      <wsdl:documentation>Read All Person Ids</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="readPersonCore">
      <wsdl:documentation>Read Person Core</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="readPersonIdsFromSavePoint">
      <wsdl:documentation>Read Person Ids From SavePoint</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="readPersons">
      <wsdl:documentation>Read all Persons</wsdl:documentation>
      <wsdl:input message="tns:readPersonsRequest.V1" name="readPersonsRequest.V1"/>
      <wsdl:output message="tns:readPersonsResponse.V1" name="readPersonsResponse.V1"/>
    </wsdl:operation>
    <wsdl:operation name="readPersonsFromSavePoint">
      <wsdl:documentation>Read persons from save point</wsdl:documentation>
      <wsdl:input message="tns:readPersonsFromSavePointReq.V1" name="readPersonsFromSavePointReq.V1"/>
      <wsdl:output message="tns:readPersonsFromSavePointRes.V1" name="readPersonsFromSavePointRes.V1"/>
    </wsdl:operation>
    <wsdl:operation name="readPerson">
      <wsdl:documentation>Read Person</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="replacePerson">
      <wsdl:documentation>Replace Person</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
    <wsdl:operation name="updatePerson">
      <wsdl:documentation>Update Person</wsdl:documentation>
      <wsdl:input message="tns:request.V1" name="request.V1"/>
      <wsdl:output message="tns:response.V1" name="response.V1"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="PERSONMANAGEMENTSERVICE_Binding" type="tns:PERSONMANAGEMENTSERVICE_PortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="changePersonIdentifier">
      <soap:operation soapAction="changePersonIdentifier.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="createByProxyPerson">
      <soap:operation soapAction="createByProxyPerson.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="createPerson">
      <soap:operation soapAction="createPerson.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="deletePerson">
      <soap:operation soapAction="DELETEPERSON_SYNC.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="discoverPersonIds">
      <soap:operation soapAction="discoverPersonIds.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readAllPersonIds">
      <soap:operation soapAction="readAllPersonIds.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readPersonCore">
      <soap:operation soapAction="readPersonCore.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readPersonIdsFromSavePoint">
      <soap:operation soapAction="readPersonIdsFromSavePoint.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readPersons">
      <soap:operation soapAction="READPERSONS.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="readPersonsRequest.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="readPersonsResponse.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readPersonsFromSavePoint">
      <soap:operation soapAction="READPERSONSFROMSAVEPOINT.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="readPersonsFromSavePointReq.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="readPersonsFromSavePointRes.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="readPerson">
      <soap:operation soapAction="readPerson.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="replacePerson">
      <soap:operation soapAction="replacePerson.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="updatePerson">
      <soap:operation soapAction="updatePerson.v1" style="document"/>
      <wsp:Policy wsu:Id="UsernameTokenSecurityPolicyPasswordOptional" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
          <wsp:All>
            <wsse:SecurityToken wsp:Usage="wsp:Required" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
              <wsse:TokenType>wsse:UserNameToken</wsse:TokenType>
              <Claims>
                <SubjectName MatchType="wsse:Exact"/>
                <UsePassword wsp:Usage="wsp:Optional"/>
              </Claims>
            </wsse:SecurityToken>
          </wsp:All>
        </wsp:ExactlyOne>
      </wsp:Policy>
      <wsdl:input name="request.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:input>
      <wsdl:output name="response.V1">
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PersonManagementServiceSyncService">
    <wsdl:documentation>Person Management Service</wsdl:documentation>
    <wsdl:port binding="tns:PERSONMANAGEMENTSERVICE_Binding" name="PERSONMANAGEMENTSERVICE_Port">
      <soap:address location="http://ORACLE_ENDPOINT"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>