ALTER TABLE SAKORA_MEMBERSHIP ADD COLUMN INPUT_INT integer NULL;
UPDATE SAKORA_MEMBERSHIP SET INPUT_INT=UNIX_TIMESTAMP(INPUT_TIME);
ALTER TABLE SAKORA_MEMBERSHIP DROP COLUMN INPUT_TIME, CHANGE COLUMN INPUT_INT INPUT_TIME integer UNSIGNED NULL DEFAULT NULL;

ALTER TABLE SAKORA_PERSON ADD COLUMN INPUT_INT integer NULL;
UPDATE SAKORA_PERSON SET INPUT_INT=UNIX_TIMESTAMP(INPUT_TIME);
ALTER TABLE SAKORA_PERSON DROP COLUMN INPUT_TIME, CHANGE COLUMN INPUT_INT INPUT_TIME integer UNSIGNED NULL DEFAULT NULL;

ALTER TABLE SAKORA_SESSION ADD COLUMN INPUT_INT integer NULL;
UPDATE SAKORA_SESSION SET INPUT_INT=UNIX_TIMESTAMP(INPUT_TIME);
ALTER TABLE SAKORA_SESSION DROP COLUMN INPUT_TIME, CHANGE COLUMN INPUT_INT INPUT_TIME integer UNSIGNED NULL DEFAULT NULL;
